name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Synchronize with the latest commit
        run: git pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Étape 4 : On exécute le script (qui est maintenant la bonne version)
      - name: Run script to update README
        run: python auto/update_readme.py

      # Étape 5 : On commite les changements (s'il y en a)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Le 'git diff' nous dira s'il y a des changements avant de commiter
          if ! git diff --staged --quiet; then
            git commit -m "Update README with new image"
            git push
          else
            echo "No changes to commit."
          fi